const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const staticRoot = path.join(__dirname, '..', '..', 'scripts', 'workbench', 'static');

test('workbench static UI explains operations in Chinese while keeping warning and error machine labels available', () => {
  const html = fs.readFileSync(path.join(staticRoot, 'index.html'), 'utf-8');
  const app = fs.readFileSync(path.join(staticRoot, 'app.js'), 'utf-8');
  const styles = fs.readFileSync(path.join(staticRoot, 'styles.css'), 'utf-8');

  assert.match(html, /提示词目录工作台/);
  assert.match(html, /修正所选问题/);
  assert.match(html, /刷新当前报告/);
  assert.match(html, /导出全语言 catalog/);
  assert.match(html, /生成全语言 README/);
  assert.match(html, /catalog-export/);
  assert.match(html, /readme-generate/);
  assert.match(html, /重新归类/);
  assert.match(html, /人工归类/);
  assert.match(html, /处理类型/);
  assert.match(html, /打包翻译/);
  assert.match(html, /batch-translation-language/);
  assert.match(html, /batch-size/);
  assert.match(html, /打包补齐所选语言/);
  assert.match(html, /class="quick-actions"/);
  assert.match(html, /操作说明/);
  assert.ok(html.indexOf('处理类型') < html.indexOf('发布输出'));
  assert.ok(html.indexOf('发布输出') < html.indexOf('智谱 AI 配置'));
  assert.ok(html.indexOf('发布输出') < html.indexOf('<aside class="panel actions">'));
  assert.doesNotMatch(styles, /max-width: 1500px/);
  assert.match(styles, /\.quick-actions/);
  assert.match(styles, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(styles, /640px/);
  assert.match(app, /全部 severity/);
  assert.match(app, /resolutionActions/);
  assert.match(app, /buildResolutionActionOptions/);
  assert.match(app, /inferResolutionAction/);
  assert.match(app, /loadCurrentAction/);
  assert.match(app, /api\/actions\/current/);
  assert.match(app, /api\/actions\/latest/);
  assert.match(app, /单条修正/);
  assert.match(app, /unclassified_category/);
  assert.match(app, /TRANSLATION_LANGUAGES/);
  assert.match(app, /batchSize/);
  assert.match(app, /scrollTop/);
  assert.match(app, /warning/);
  assert.match(app, /error/);
});
